Repository stratum/stratum, pull requests merged in 2020-06, with the labels that each got.

#224 Cleanup TAI implementation
  .reuse/dep5
  README.md
  bazel/deps.bzl
  bazel/external/taish_proto.BUILD
  stratum/docs/tai/README.md
  stratum/docs/tai/img/overview.svg
  stratum/docs/tai/img/terminology.svg
  stratum/docs/tai/imgsrc/overview.graphml
  stratum/docs/tai/imgsrc/terminology.graphml
  stratum/hal/bin/bcm/standalone/BUILD
  stratum/hal/bin/dummy/chassis_config
  stratum/hal/lib/bcm/bcm_switch.cc
  stratum/hal/lib/common/common.proto
  stratum/hal/lib/common/gnmi_events.h
  stratum/hal/lib/common/phal_interface.h
  stratum/hal/lib/common/phal_mock.h
  stratum/hal/lib/common/utils.cc
  stratum/hal/lib/common/utils.h
  stratum/hal/lib/common/yang_parse_tree.cc
  stratum/hal/lib/common/yang_parse_tree.h
  stratum/hal/lib/common/yang_parse_tree_paths.cc
  stratum/hal/lib/common/yang_parse_tree_paths.h
  stratum/hal/lib/common/yang_parse_tree_test.cc
  stratum/hal/lib/dummy/BUILD
  stratum/hal/lib/dummy/dummy_phal.cc
  stratum/hal/lib/dummy/dummy_phal.h
  stratum/hal/lib/dummy/dummy_switch.cc
  stratum/hal/lib/phal/db.proto
  stratum/hal/lib/phal/optics_adapter.cc
  stratum/hal/lib/phal/optics_adapter.h
  stratum/hal/lib/phal/optics_adapter_test.cc
  stratum/hal/lib/phal/phal.cc
  stratum/hal/lib/phal/phal.h
  stratum/hal/lib/phal/phal.proto
  stratum/hal/lib/phal/phal_sim.cc
  stratum/hal/lib/phal/phal_sim.h
  stratum/hal/lib/phal/tai/BUILD
  stratum/hal/lib/phal/tai/tai_interface.h
  stratum/hal/lib/phal/tai/tai_interface_mock.h
  stratum/hal/lib/phal/tai/tai_optics_datasource.cc
  stratum/hal/lib/phal/tai/tai_optics_datasource.h
  stratum/hal/lib/phal/tai/tai_optics_datasource_test.cc
  stratum/hal/lib/phal/tai/tai_phal.cc
  stratum/hal/lib/phal/tai/tai_phal.h
  stratum/hal/lib/phal/tai/tai_phal_test.cc
  stratum/hal/lib/phal/tai/tai_switch_configurator.cc
  stratum/hal/lib/phal/tai/tai_switch_configurator.h
  stratum/hal/lib/phal/tai/tai_switch_configurator_test.cc
  stratum/hal/lib/phal/tai/taish_client.cc
  stratum/hal/lib/phal/tai/taish_client.h
Labels: P1, TAI

#245 Add section about partial chassis configs with BCM
  stratum/hal/bin/bcm/standalone/README.md
Labels: Configs, P1

#251 Bump Bazel version to 3.2.0
  Dockerfile.build
Labels: P2

#257 Pin cpplint version until cpplint/cpplint#146 is fixed
  Dockerfile.build
Labels: P1

#263 Update cpplint
  Dockerfile.build
Labels: P1

#266 Add `kdir` param to BF README.md
  stratum/hal/bin/barefoot/README.md
Labels: documentation

#211 Add buildifier and run as non-mandatory CI job
  .circleci/config.yml
  CONTRIBUTING.md
  Dockerfile.build
Labels: Infra, P2, enhancement
