Repository stratum/stratum, pull requests merged in 2020-04, with the labels that each got.

#155 Implement SDKLT config file (.yaml) generator
  bazel/deps.bzl
  stratum/hal/lib/bcm/BUILD
  stratum/hal/lib/bcm/bcm_chassis_manager.cc
Labels: Configs

#177 Add loopback mode to the Stratum model
  stratum/docs/gnmi/supported-paths.md
  stratum/hal/lib/common/openconfig_converter.cc
  stratum/hal/lib/common/testdata/port_config_params_chassis.pb.txt
  stratum/hal/lib/common/testdata/port_config_params_oc_device.pb.txt
  stratum/public/yang/openconfig-interfaces-stratum.yang
Labels: gNMI

#176 Improve Barefoot conatiner image build script
  stratum/hal/bin/barefoot/docker/Dockerfile.builder
  stratum/hal/bin/barefoot/docker/Dockerfile.runtime
  stratum/hal/bin/barefoot/docker/build-kdrv.sh
  stratum/hal/bin/barefoot/docker/build-stratum-bf-container.sh
Labels: Infra, enhancement

#179 Remove dangling image only
  stratum/hal/bin/barefoot/docker/build-stratum-bf-container.sh
Labels: Infra

#173 Add loopback support for BF devices
  stratum/hal/lib/barefoot/bf_chassis_manager.cc
  stratum/hal/lib/barefoot/bf_chassis_manager.h
  stratum/hal/lib/barefoot/bf_chassis_manager_test.cc
  stratum/hal/lib/barefoot/bf_pal_interface.h
  stratum/hal/lib/barefoot/bf_pal_mock.h
  stratum/hal/lib/barefoot/bf_pal_wrapper.cc
  stratum/hal/lib/barefoot/bf_pal_wrapper.h
  stratum/hal/lib/barefoot/bf_switch.cc
Labels: enhancement, gNMI

#144 Fix z9100 base chassis map and add config.bcm
  stratum/hal/config/x86-64-dell-z9100-c2538-r0/base_bcm_chassis_map.pb.txt
  stratum/hal/config/x86-64-dell-z9100-c2538-r0/config.bcm
Labels: Configs

#212 Move to IANA-reserved port 9339 for gNMI/gNOI
  stratum/hal/bin/barefoot/README.md
  stratum/hal/bin/barefoot/docker/Dockerfile.runtime
  stratum/hal/bin/barefoot/docker/start-stratum-container.sh
  stratum/hal/bin/barefoot/docker/stratum.flags
  stratum/hal/bin/bcm/standalone/docker/Dockerfile
  stratum/hal/bin/bcm/standalone/start-stratum.sh
  stratum/hal/bin/bmv2/README.md
  stratum/hal/bin/bmv2/stratum_bmv2.environment
  stratum/hal/bin/bmv2/stratum_bmv2.service
  stratum/hal/bin/dummy/README.md
  stratum/hal/lib/common/hal.cc
  stratum/lib/constants.h
  stratum/pipelines/README.md
  stratum/pipelines/ptf/ptf_exec.py
  stratum/testing/scenarios/README.md
  stratum/testing/scenarios/scenarios.cc.tmpl
  tools/gnmi/gnmi_cli.cc
Labels: P1, Ready for Review, gNMI, gNOI

#193 Add TLS/SSL support
  .gitignore
  README.md
  stratum/hal/bin/barefoot/main.cc
  stratum/hal/bin/bcm/sim/main.cc
  stratum/hal/bin/bcm/standalone/main.cc
  stratum/hal/bin/bmv2/main.cc
  stratum/hal/bin/dummy/main.cc
  stratum/lib/security/BUILD
  stratum/lib/security/README.md
  stratum/lib/security/credentials_manager.cc
  stratum/lib/security/credentials_manager.h
  stratum/lib/security/credentials_manager_mock.h
  tools/gnmi/README.md
  tools/gnmi/gnmi_cli.cc
  tools/tls/ca.conf
  tools/tls/generate-certs.sh
  tools/tls/grpc-client.conf
Labels: P1, Ready for Review

#206 Add rules for py proto files and package them
  .circleci/config.yml
  tools/mininet/Dockerfile
Labels: P1

#217 Add `m` utility to mn-stratum image
  tools/mininet/Dockerfile
  tools/mininet/examples/trellis/Makefile
  tools/mininet/examples/trellis/README.md
Labels: P3, Ready for Review, enhancement
