Repository stratum/stratum, pull requests merged in 2020-05, with the labels that each got.

#220 Add chassis_config, chassis_map & phal_config for Inventec d7054
  stratum/hal/config/BUILD
  stratum/hal/config/x86-64-inventec-d7054q28b-r0/base_bcm_chassis_map.pb.txt
  stratum/hal/config/x86-64-inventec-d7054q28b-r0/chassis_config.pb.txt
  stratum/hal/config/x86-64-inventec-d7054q28b-r0/phal_config.pb.txt
Labels: Ready for Review

#202 Debian package for Barefoot Tofino-based platform
  .reuse/dep5
  stratum/hal/bin/barefoot/BUILD
  stratum/hal/bin/barefoot/README.md
  stratum/hal/bin/barefoot/deb/postinst
  stratum/hal/bin/barefoot/deb/prerm
  stratum/hal/bin/barefoot/deb/stratum-entrypoint
  stratum/hal/bin/barefoot/deb/stratum.flags
  stratum/hal/bin/barefoot/deb/stratum_bf.env
  stratum/hal/bin/barefoot/deb/stratum_bf.service
  stratum/hal/bin/barefoot/docker/Dockerfile.builder
  stratum/hal/bin/barefoot/docker/Dockerfile.runtime
  stratum/hal/bin/barefoot/docker/README.md
  stratum/hal/bin/barefoot/docker/build-kdrv.sh
  stratum/hal/bin/barefoot/docker/build-stratum-bf-container.sh
  stratum/hal/bin/barefoot/docker/start-stratum-container.sh
  stratum/hal/bin/barefoot/docker/stratum-entrypoint.sh
  stratum/hal/bin/barefoot/docker/stratum.flags
  stratum/hal/lib/barefoot/barefoot.bzl
Labels: P1, Ready for Review

#201 Dev/netcope
  .circleci/test-targets.txt
  .reuse/dep5
  Dockerfile.np4intel.dev
  README.md
  WORKSPACE
  bazel/deps.bzl
  build_np4intel_image.sh
  setup_dev_env.sh
  stratum/hal/bin/np4intel/BUILD
  stratum/hal/bin/np4intel/docker/.gitignore
  stratum/hal/bin/np4intel/docker/Dockerfile.builder
  stratum/hal/bin/np4intel/docker/Dockerfile.runtime
  stratum/hal/bin/np4intel/docker/Dockerfile.runtime.local
  stratum/hal/bin/np4intel/docker/README.md
  stratum/hal/bin/np4intel/docker/build-stratum-np4intel-container.sh
  stratum/hal/bin/np4intel/docker/configs/chassis_config.pb.txt
  stratum/hal/bin/np4intel/docker/configs/device_configs/device_config_node_id_1.pb.txt
  stratum/hal/bin/np4intel/docker/configs/device_configs/device_config_node_id_1.pb.txt.map
  stratum/hal/bin/np4intel/docker/configs/device_configs/device_config_node_id_2.pb.txt.sample
  stratum/hal/bin/np4intel/docker/configs/device_configs_daemon/device_config_node_id_1.pb.txt
  stratum/hal/bin/np4intel/docker/configs/dpdk_config.pb.txt
  stratum/hal/bin/np4intel/docker/configs/p4info_np4.txt
  stratum/hal/bin/np4intel/docker/configs/pipeline_config.pb.txt
  stratum/hal/bin/np4intel/docker/configs/stratum.flags
  stratum/hal/bin/np4intel/docker/patches/CMakeLists.txt.patch
  stratum/hal/bin/np4intel/docker/patches/bmcdata.c.patch
  stratum/hal/bin/np4intel/docker/patches/dependency_notifier.cmake.patch
  stratum/hal/bin/np4intel/docker/scripts/build_pipeline_configs.py
  stratum/hal/bin/np4intel/docker/scripts/init_system.sh
  stratum/hal/bin/np4intel/docker/scripts/stratum-entrypoint.sh
  stratum/hal/bin/np4intel/docker/scripts/tr_p4info.py
  stratum/hal/bin/np4intel/docker/start-stratum-container.sh
  stratum/hal/bin/np4intel/dpdk_config.proto
  stratum/hal/bin/np4intel/dummy.json
  stratum/hal/bin/np4intel/main.cc
  stratum/hal/bin/np4intel/np4intel.bzl
  stratum/hal/lib/common/common.proto
  stratum/hal/lib/np4intel/BUILD
  stratum/hal/lib/np4intel/np4_chassis_manager.cc
  stratum/hal/lib/np4intel/np4_chassis_manager.h
  stratum/hal/lib/np4intel/np4_chassis_manager_test.cc
  stratum/hal/lib/np4intel/np4_switch.cc
  stratum/hal/lib/np4intel/np4_switch.h
  stratum/hal/lib/np4intel/test_main.cc
  stratum/hal/lib/pi/BUILD
Labels: P1, Ready for Review

#196 Add Stratum BCM feature guide
  stratum/docs/extenting_stratum_bcm.md
Labels: P1

#115 PhalCli: Better path parsing
  stratum/hal/lib/phal/BUILD
  stratum/hal/lib/phal/phal_cli.cc
Labels: P1, PHAL, Ready for Review

#231 Update Abseil dependency
  bazel/deps.bzl
Labels: P1

#232 Minor cleanup of NP4 related code
  .circleci/build-targets.txt
  .circleci/test-targets.txt
  stratum/hal/bin/bmv2/main.cc
  stratum/hal/bin/np4intel/main.cc
  stratum/hal/lib/np4intel/BUILD
  stratum/hal/lib/np4intel/np4_chassis_manager.cc
  stratum/hal/lib/np4intel/np4_switch.cc
  stratum/hal/lib/np4intel/test_main.cc
Labels: P1, enhancement

#228 Misc code cleanup and fixes for minor targets
  .circleci/build-targets.txt
  .circleci/test-targets.txt
  stratum/hal/lib/phal/BUILD
  stratum/hal/lib/phal/phal_cli.cc
  stratum/hal/stub/embedded/BUILD
  stratum/hal/stub/embedded/main.cc
  stratum/pipelines/main/main.p4
  stratum/public/lib/BUILD
  stratum/public/model/BUILD
  stratum/public/proto/BUILD
  stratum/public/proto/proto2/BUILD
  stratum/testing/cdlang/BUILD
  stratum/testing/cdlang/antlr.bzl
  stratum/testing/cdlang/cdlang.bzl
  stratum/testing/cdlang/deps.bzl
  stratum/testing/protos/BUILD
  stratum/testing/scenarios/BUILD
  stratum/testing/scripts/BUILD
  stratum/testing/scripts/do_nothing.sh
  stratum/testing/tests/BUILD
  stratum/testing/tests/bcm_sim_test.cc
  stratum/testing/tests/bcm_sim_test_fixture.cc
  stratum/testing/tests/bcm_sim_test_fixture.h
  stratum/testing/tests/test_main.cc
Labels: P2, enhancement

#236 Add link to online html OpenConfig models
  stratum/docs/gnmi/README.md
Labels: P2, documentation, gNMI

#248 Symlink SerDes firmware in tarball
  bazel/rules/package_rule.bzl
  stratum/hal/lib/barefoot/barefoot.bzl
Labels: P1

#249 Transform inline BUILD files of external deps to real files
  bazel/external/bfsde.BUILD
  bazel/external/bmv2.BUILD
  bazel/external/np4intel.BUILD
  bazel/external/onlp.BUILD
  bazel/external/onlp_local.BUILD
  stratum/hal/bin/bmv2/bmv2.bzl
  stratum/hal/bin/np4intel/np4intel.bzl
  stratum/hal/lib/barefoot/barefoot.bzl
  stratum/hal/lib/phal/onlp/onlp.bzl
Labels: Infra, P2, enhancement
