Repository stratum/stratum, pull requests merged in 2020-09, with the labels that each got.

#317 Address concerns about yang chip type feature
  stratum/glue/gtl/stl_util.h
  stratum/hal/lib/bcm/bcm_switch.cc
  stratum/hal/lib/bcm/utils.cc
  stratum/hal/lib/bcm/utils.h
  stratum/hal/lib/bcm/utils_test.cc
  stratum/hal/lib/common/BUILD
  stratum/hal/lib/common/config_monitoring_service.cc
  stratum/hal/lib/common/config_monitoring_service.h
  stratum/hal/lib/common/yang_parse_tree_paths.cc
Labels: P1, enhancement, gNMI

#332 Add IANA port for P4RT to default external port list
  stratum/docs/setup_guide_barefoot_tofino_onos.md
  stratum/hal/bin/barefoot/README.md
  stratum/hal/bin/barefoot/docker/Dockerfile.runtime
  stratum/hal/bin/barefoot/docker/start-stratum-container.sh
  stratum/hal/bin/bcm/standalone/docker/Dockerfile
  stratum/hal/bin/bmv2/README.md
  stratum/hal/bin/np4intel/docker/Dockerfile.runtime
  stratum/hal/bin/np4intel/docker/Dockerfile.runtime.local
  stratum/hal/bin/np4intel/docker/README.md
  stratum/hal/bin/np4intel/docker/start-stratum-container.sh
  stratum/lib/constants.h
Labels: P1

#344 Fix Mininet Dockerfile
  tools/mininet/Dockerfile
Labels: P1, bug

#328 Report packetout errors to controller
  stratum/hal/lib/common/p4_service.cc
  stratum/hal/lib/common/p4_service.h
  stratum/hal/lib/common/p4_service_test.cc
Labels: P1, P4/P4Runtime, enhancement
